### ISSUE TITLE
Provider Support for OpenStack

### ISSUE THREAD

**Issue by vi-patel** [rhpit/manageiq-cli#11]
Have CLI support for the OpenStack provider.
Support to create, teardown, add networking capabilities, query the resource (vm)

**Comment by tvieira** [comment]
@vi-patel can you describe what else is needed for this ticket?

**Comment by vi-patel** [comment]
This ticket can be closed as we support all the stated functionality for the OpenStack provider:

- ability to provision (create provision requests)
- ability to query instances for Openstack
- ability to support network (add or remove floating ips) 
- ability to teardown (delete instances) in OpenStack
