### ISSUE TITLE
Query details for provisioned resource(s)

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#12]
The CLI should provide the ability to query information related to provisioned resources. Resources will provide different information regarding the provider it was provisioned into.

I.e. query the host name for an instance or the public IP address to access the instance via SSH.

**Comment by vi-patel** [comment]
@smatula, @rywillia, @tvieira   do you think we can close this ticket? I believe this feature is available will all of the options that the user has to query an instance. There are basic examples of usage in the provisioning examples for OpenStack and AWS of how to get the floating ip from an instance.

**Comment by tvieira** [comment]
+1 to close it.

**Comment by ryankwilliams** [comment]
+1 also for me to close.
