### ISSUE TITLE
Teardown a Resource

### ISSUE THREAD

**Issue by vi-patel** [rhpit/manageiq-cli#14]
support for an option to teardown a resource

**Comment by ryankwilliams** [comment]
References #114

**Comment by ryankwilliams** [comment]
@vi-patel Is it okay to close this issue? Now that both implementations for deleting resources in Amazon/OpenStack providers are checked in?

**Comment by vi-patel** [comment]
Closing this ticket as we have deletion examples available for both supported providers.
