### ISSUE TITLE
Validate resources to be provisioned

### ISSUE THREAD

**Issue by vi-patel** [rhpit/manageiq-cli#18]
Validate all the input for the resource that is to be provisioned:

- image, size, etc...

**Comment by tvieira** [comment]
Do we know how we want to validate resources before we request it? What is the strategy?

**Comment by vi-patel** [comment]
I was thinking that we should just submit the provisioning request, which will first do a lookup of all the user's input prior to submitting the request, as it needs the ids not name values. If any data is not valid we will get an error and the code would abort saying what was invalid (for example if there was a typo in the input, we would get an error when attempting provisioning request: Flavor m1.msall not found for provider OpenStack), and a provision request would never be created.  Is this satisfactory?

**Comment by tvieira** [comment]
> Is this satisfactory?

I think so.  Any input @rywillia @smatula ?

**Comment by ryankwilliams** [comment]
I agree with @vi-patel comment. I think that should be enough for an initial resource validation since we are required to use the ID for a given resource to perform some action via REST API.

@vi-patel Majority of this issue is already implemented correct?

**Comment by vi-patel** [comment]
I believe this is implemented for all of the options for AWS and OpenStack in the provisioning request @rywillia, @tvieira, is this good enough to close the ticket, and we can add tickets for other providers as they become supported?

**Comment by ryankwilliams** [comment]
@vi-patel Okay by me to close this issue. Since our initial supported providers already handle this validation.

**Comment by tvieira** [comment]
OK by me to close the ticket too.
