### ISSUE TITLE
Host the CLI documentation

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#25]
Currently the project is using sphinx to document all of its documentation for the CLI. This issue is to determine and put in place how we plan to host the documentation. Some possible suggestions are:

- GitHub Pages
- Read the Docs

The nice take away with read the docs is it provides the ability to have versioned documentation. This way if users want to stick with a certain version of the CLI, they can follow the documentation that aligns with it. As far as I know, GitHub Pages does not provide this capability out of the box. I did find a sphinx versioning tool [1] that may be possible to provide this capability for GitHub Pages hosting the documentation.

[1] https://robpol86.github.io/sphinxcontrib-versioning/index.html#

**Comment by tehsmyers** [comment]
I've requested authorization from RTD. That might not be an ideal setup, and I understand if rhpit owners aren't comfortable with setting up rtd access in this way. Please disregard/deny the request if so.

**Comment by tvieira** [comment]
granted!
