### ISSUE TITLE
ManageIQ/Cloudforms Authentication

### ISSUE THREAD

**Issue by vi-patel** [rhpit/manageiq-cli#33]
From Tiago's comments on a previous issue, on how we should authenticate to the server:

We should have a token set in a temporary file to assist the command line to connect to the ManageIQ instance. But this is the responsibility of the CLI and not the user. The user has to provide only the username, password and the host wheren ManageIQ is installed.

The order for the token should be something like:

if a $HOME/.miqcli/auth file exist
  validate token
  if token doesn't work
    create new token
    update $HOME/.miqcli/auth
else
  create  $HOME/.miqcli/auth
  create new token
  update $HOME/.miqcli/auth
use token from $HOME/.miqcli/auth

**Comment by vi-patel** [comment]
After some research, I believe the authentication should work as follows:

1. If a user supplies a token, attempt to auth w/the token and if it fails, authentication will fail
2. If the user does not supply a token, check for $HOME/.miqcli/auth file
   validate that it is good,
   if not use, passed username/password to generate a new token, and update $HOME/.miqcli/auth
  else
     auth fails
3. create $HOME/.miqcli/auth
    use username/password to generate a new token, and update $HOME/.miqcli/auth

On the server side, the admin will have control over how long the tokens are valid for, default is 10 minutes:
Configuration -> Settings -> Zones (Server Zone) -> Advanced

API:
:api:
  :token_ttl: 10.minutes
  :authentication_timeout: 30.seconds

**Comment by tvieira** [comment]
> If a user supplies a token, attempt to auth w/the token and if it fails, authentication will fail

Where would the user get the token to be able to supply it?

**Comment by ryankwilliams** [comment]
That would require the user to do a [REST API](http://manageiq.org/docs/reference/latest/doc-REST_API/miq/#using-authentication-tokens) call to retrieve the authenticated token from their username/password. Then supply the token to the CLI.

**Comment by vi-patel** [comment]
I assume this won't be used by most, but I believe if a user doesn't want to pass our client their username and password they would attempt to get a token, and use that.  As Ryan said just a REST API call, by going to the url (https://<manageiq_server)/api/auth) and passing creds or a direct REST call w/creds passed)

**Comment by tvieira** [comment]
OK, so the algorithm in the comment (my comment) above should change understanding you also expect the user will provide a token. I let you @vi-patel to fix that.
