### ISSUE TITLE
Define how we will connect to ManageIQ

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#34]
In order for issue #23 to be started, we need to determine where we will establish the connection to the ManageIQ server defined by the user. Before the new year I started working on a prototype on how we could incorporate the ManageIQ API Client library but came across a problem. We can't establish the connection within the constructor for each collection class. If this is done, every time you run the CLI it would attempt to establish a connection to the server. This would potentially cause a DOS attack against your ManageIQ server. I.e. users install the client and run the client over and over to view the commands. It would be attempting to connect each time.

```bash
# connection would be attempted when running this command
$ miqcli <command>
```
I found that we can override the parent invoke method for the CLI sub-command class. This could allow us to perform the initial connection to ManageIQ (calling a method from a API class). Having this method available to be run at any point within the CLI is good because we may need to establish a connection again if a given token has expired.

I.e. When we are within the sub collections class we already know the command being run and have the command object. We can easily call a method to connect to the server.

```python
class SubCollections(click.MultiCommand):

    def invoke(self, ctx):
        """Invoke the sub-command selected.

        Runs the sub-command given with all its arguments. Before it invokes
        the sub-command action to run, it will attempt to establish a
        connection to ManageIQ.

        :param ctx: Click context.
        :type ctx: Namespace
        """
        self.collection.connect()
        super(SubCollections, self).invoke(ctx)
```

**Comment by tvieira** [comment]
I have to better understand the `invoke` function, what I say below may not be necessary. As far as I get from Click, you can use [context](http://click.pocoo.org/5/api/#context). From its API docs:

> The context is a special internal object that holds state relevant for the script execution at every single level. It’s normally invisible to commands unless they opt-in to getting access to it.
> 
> The context is useful as it can pass internal objects around and can control special execution features such as reading data from environment variables.
> 
> A context can be used as context manager in which case it will call close() on teardown.

Once the command is called, can a Context object holds a `MiqApi` ([example](https://github.com/ManageIQ/manageiq-api-client-python/blob/03a029b6e9741d7cf4cdf482a40fff7ecd263b34/example.py#L13)) client pointer?

The only thing we have to take care when creating the `MiqApi` client pointer is to test if the token is still valid. If not, we use the username and password, set the token as explained in #33, and then use the token onwards.

Does it make sense?  I think around half-dozen calls for each command we run won't stress the server. Do we have any reference or a load test report from ManageIQ to understand how much load a single server can handle?

**Comment by ryankwilliams** [comment]
@tvieira That is correct, click's context is very powerful when it comes to being able to save data to be accessed at any point. I choose not to save the MiqApi client pointer within the context because I thought its scope should live within the collection classes. The collection classes would be the ones needing the MiqApi client pointer. When the CLI is about to invoke (run) the command, it already has the command (collection class object) created. That was why I choose to save the client pointer connection within the object over context.

I do not have any reference or load test reports from ManageIQ on understanding the amount of connections the server can handle. My guess would be it can handle a significant amount of traffic. From a coding standpoint, I felt it was not the best design if we would be attempting to connect to ManageIQ each time the CLI is run to view its commands/sub-commands. That was why I override the click.MultiCommand invoke method to first attempt to connect to ManageIQ when the CLI gets the go ahead to run the command and its given parameters.

I totally agree on your comment about testing if the token is valid based on #33. I added a TODO in the code for us to handle that when creating the MiqApi client pointer.
