### ISSUE TITLE
Create the contributing guidelines

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#4]
Create the CONTRIBUTING doc at the root of the project. This will define all the guidelines that existing and new contributors need to follow by when submitting pull requests.

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by ryankwilliams** [comment]
I started to work on an initial draft for the contributing guidelines. The draft can be found below if anyone wants to take a look or use as a base for the doc.

https://github.com/rywillia/manageiq-cli/blob/contributing-edits/CONTRIBUTING.rst

**Comment by tehsmyers** [comment]
LGTM, but there's a nit: Line 82 is outdented, so it doesn't render correctly in the bulleted list.

**Comment by ryankwilliams** [comment]
@seandst Thank you for the feedback and I will make the change to fix the list indentation.
