### ISSUE TITLE
We need automation to run local tests

### ISSUE THREAD

**Issue by tvieira** [rhpit/manageiq-cli#40]
We have created a tox file to run tests in Python 3.6 + 2.7 + PEP8 standards check, but now we need an instance of ManageIQ running locally so we can run tests locally prior to create a new PR for the feature/fix. 

There are few options that I have been testing:

1. Vagrant + ManageIQ image (http://manageiq.org/docs/get-started/vagrant)
2. Docker + ManageIQ image (http://manageiq.org/docs/get-started/docker)
3. Local machine installation

The 3rd option I would discard, I don't want to install and maintain a local installation of ManageIQ and I don't think anyone would want that.

The 1st and 2nd options are a lot easier to manage. I would adopt docker because when using Vagrant we still have to have Virtualbox. Some of us will have only libvirt, or VMWare and there's no official image available for these providers.

I would vote for Docker as, at least the core developers for this project, we all have the technology locally to run containers.

Is there anyone that would prefer another option other than using the docker image created by ManageIQ? Otherwise I already have some work done with the docker image.

**Comment by ryankwilliams** [comment]
@tvieira I agree with you on the option for testing locally. I would also go with Docker + ManageIQ image.
