### ISSUE TITLE
tox fails to build sphinx documentation

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#5]
While working on issue #3 to enable a CI job for each pull request. I noticed the tox command would fail when it comes to building the sphinx documentation. The doc generator fails because the **static** folder does not exist. Console output below:

```bash
Running Sphinx v1.6.5
loading pickled environment... failed: unsupported pickle protocol: 4
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index

generating indices... genindex
writing additional pages... search
copying static files... 
Warning, treated as error:
html_static_path entry u'/home/rywillia/github/manageiq-cli/doc/source/static' does not exist
ERROR: InvocationError: '/home/rywillia/github/manageiq-cli/.tox/docs/bin/python setup.py build_sphinx'
________________________________________________ summary ________________________________________________
  py36: commands succeeded
  py27: commands succeeded
  pep8: commands succeeded
ERROR:   docs: commands failed
```
There are two ways we can resolve this:

1. Commit the static folder with a empty place holder **.gitkeep**.

2. We can modify the docs conf.py module to remove the static folder from the **html_static_path** variable.

```bash
 # Add any paths that contain custom static files (such as style sheets) here,
 # relative to this directory. They are copied after the builtin static files,
 # so a file named "default.css" will overwrite the builtin "default.css".
-html_static_path = ['static']
+html_static_path = []
```
I would suggest suggestion 1: to add an empty place holder. Reason being is when the documentation grows, we probably will have static files that will need to be included during the doc build process. This way then we do not need to edit the conf.py adding back the static folder to the path. @tvieira what are your thoughts on this?

**Comment by tvieira** [comment]
Ignored my past comments. I would leave static with `.gitkeep`. We currently don't have static files but it is nice to keep them separated.
