### ISSUE TITLE
Attempting to load an empty configuration file throws an exception

### ISSUE THREAD

**Issue by ryankwilliams** [rhpit/manageiq-cli#50]
The first item the CLI tackles is handling reading configuration data that the user can set. User can set this data either in a file format, environment variable or as CLI global parameter options. I was testing the Config class which handles these actions and found when I have the directory **/etc/miqcli** created and an a empty file **miqcli.yml** created. It fails when trying to parse the file when it is empty.

Need to handle the use case where the file may be empty and  we should ignore trying to parse it.

```bash
(miq-py36) [rywillia@laptop ~]$ tree /etc/miqcli/
/etc/miqcli/
└── miqcli.yml

0 directories, 1 file

(miq-py36) [rywillia@laptop ~]$ stat /etc/miqcli/miqcli.yml 
  File: /etc/miqcli/miqcli.yml
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd01h/64769d	Inode: 1716768     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/rywillia)   Gid: ( 1000/rywillia)
Context: unconfined_u:object_r:etc_t:s0
Access: 2018-01-11 10:56:06.944662412 -0500
Modify: 2018-01-11 10:55:58.056608016 -0500
Change: 2018-01-11 10:55:58.056608016 -0500
 Birth: -

(miq-py36) [rywillia@laptop ~]$ miqcli 
Traceback (most recent call last):
  File "/home/rywillia/.virtualenvs/miq-py36/bin/miqcli", line 6, in <module>
    from miqcli.cli.main import cli
  File "/home/rywillia/github/manageiq-cli/miqcli/cli/main.py", line 224, in <module>
    silent=True)
  File "/home/rywillia/github/manageiq-cli/miqcli/utils/__init__.py", line 74, in from_yaml
    for key in config_data:
TypeError: 'NoneType' object is not iterable
```

**Comment by tvieira** [comment]
Would adding 

```python
if config_data is not None:
```

before `for key in config_data:` solve this? I did a quick test and it worked. 

The correct approach would start writing tests :))

**Comment by ryankwilliams** [comment]
@tvieira Thanks for providing the solution! :+1: to the tests :)
