### ISSUE TITLE
Document AWS subnet workaround for provisioning AWS instances via ManageIQ REST API

### ISSUE THREAD

**Issue by tvieira** [rhpit/manageiq-cli#81]
We have to create Ruby scripts to automate the creation of AWS subnet just like we did for creating Floating IPs at Openstack (#27). We want to have this documented to assist us when we deploy a stage instance of ManageIQ for testing purpose.

**Comment by smatula** [comment]
It's more simple than it is for the floating IP's on openstack.  The subnets are expected to be already configured. When we provision we our required to specify a subnet. Expected Input by user will be by name. No rest API to access the cloud_subnets on cloudforms. Need to create an automate method to perform a lookup and return the id so we may provide it to the provision request just like is being done for other fields.

**Comment by smatula** [comment]
Not an issue. Discovered correct way to obtain cloud_subnet information through the Rest API.
