### ISSUE TITLE
Attribute Error for caught Exception when passing an invalid Settings file

### ISSUE THREAD

**Issue by vi-patel** [rhpit/manageiq-cli#92]
calling any miqcli command, when there is an invalid credentials file results in an attribute error for the caught exception:

  File "/home/vipatel/PycharmProjects/manageiq-cli/miqcli/utils/__init__.py", line 82, in from_yml
    log.debug('Standard error: {0}'.format(e.sterror))
AttributeError: 'ParserError' object has no attribute 'sterror'

**Comment by ryankwilliams** [comment]
I can reproduce this exception when my settings file is loaded by the `yaml` module returning the file content back as a string data type. This exception can be avoided with a check to verify the file content data type is valid.

File content that I used to reproduce the bug:

```yaml
---
url; https://localhost:8443
```
```yaml
url    https://localhost:8443
```
